name: BiTGApps Build

on:
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.TOKEN }}
  RELEASE: v1.6

jobs:
  build:
    if: github.repository_owner == 'BiTGApps'
    runs-on: ubuntu-latest

    steps:
       - name: Initial Setup
         uses: actions/checkout@v2

       - name: Create BiTGApps
         run: |
           rm -rf BiTGApps
           mkdir BiTGApps
           install -d out

       - name: Clone Build Sources
         run: |
           git clone https://github.com/BiTGApps/BiTGApps-Uninstaller BiTGApps

       - name: Build BiTGApps Package
         run: |
           cd BiTGApps
           . scripts/envsetup.sh && rm -rf scripts
           zip -qr9 BiTGApps-$RELEASE.zip * && cd ..
           cp -f BiTGApps/BiTGApps-$RELEASE.zip out

       - name: Sign BiTGApps Package
         run: |
           wget https://github.com/BiTGApps/BiTGApps/raw/master/tools/zipsigner/zipsigner.jar
           sudo java -jar zipsigner.jar out/BiTGApps-$RELEASE.zip out/BiTGApps-$RELEASE-Signed.zip
           rm -rf out/BiTGApps-$RELEASE.zip && mv -f out/BiTGApps-$RELEASE-Signed.zip out/BiTGApps-$RELEASE.zip

       - name: Github Release CLI
         run: |
           npm install -g github-release-cli

       - name: Release Signed Package
         env:
           PACKAGE: false
         run: |
           github-release upload \
           --owner "BiTGApps" \
           --repo "BiTGApps-Uninstaller" \
           --token "$TOKEN" \
           --tag "${RELEASE}" \
           --release-name "BiTGApps ${RELEASE}" \
           "out/BiTGApps-$RELEASE.zip"

       - name: Upload Build Artifact
         if: ${{ env.PACKAGE == 'true' }}
         uses: actions/upload-artifact@v3
         with:
           name: BiTGApps-Build
           path: out/BiTGApps-$RELEASE.zip
