name: BiTGApps Build

on:
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    if: github.repository_owner == 'BiTGApps'
    runs-on: ubuntu-latest

    steps:
       - name: Initial Setup
         uses: actions/checkout@v2

       - name: Create BiTGApps
         run: |
           rm -rf BiTGApps
           mkdir BiTGApps
           install -d out

       - name: Clone Build Sources
         run: |
           git clone https://github.com/BiTGApps/BiTGApps-Uninstaller BiTGApps

       - name: Build BiTGApps Package
         run: |
           cd BiTGApps
           . scripts/envsetup.sh && rm -rf scripts
           zip -qr9 BiTGApps-v1.5.zip * && cd ..
           cp -f BiTGApps/BiTGApps-v1.5.zip out

       - name: Sign BiTGApps Package
         run: |
           wget https://github.com/BiTGApps/BiTGApps/raw/master/tools/zipsigner/zipsigner.jar
           sudo java -jar zipsigner.jar out/BiTGApps-v1.5.zip out/BiTGApps-v1.5-Signed.zip
           rm -rf out/BiTGApps-v1.5.zip && mv -f out/BiTGApps-v1.5-Signed.zip out/BiTGApps-v1.5.zip

       - name: Github Release CLI
         run: |
           npm install -g github-release-cli

       - name: Release Signed Package
         env:
           RELEASE: v1.5
         run: |
           github-release upload \
           --owner "BiTGApps" \
           --repo "BiTGApps-Uninstaller" \
           --token "$TOKEN" \
           --tag "${RELEASE}" \
           --release-name "BiTGApps ${RELEASE}" \
           "out/BiTGApps-v1.5.zip"

       - name: Upload Build Artifact
         uses: actions/upload-artifact@v2
         with:
           name: BiTGApps-Build
           path: out/BiTGApps-v1.5.zip
